### ISSUE TITLE
Need Help on Cors

### ISSUE THREAD

**Issue by sameersanatkpatro** [iris-contrib/middleware#13]
Hi @kataras ,
I know this Question have been asked multiple times.But I am not able to understand how to implement the Iris.Any.
I have implemented my frontend in react and backend in iris.
When I am trying a PUT its throws CORS issue.
Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3333' is therefore not allowed access

I have configured CORS:

app := iris.New()
app.Use(cors.DefaultCors())

The API are as follows:
app.Post("/user/create",func(c *iris.Context){//db.insert...}
app.Put("/user/edit/:email",func(c *iris.Context){//db.update...}
.....
I have read on the previous answers that we need to user Iris.Any.
Can you please tell me how the Iris.Any will be implemented for the Api's above?Thanks in advance for your help.

**Comment by kataras** [comment]
@sameersanatkpatro `cors.DefaultCors()` accepts only those two methods for cors: []string{"GET", "POST"} 

you have to call it with options:

`cors.New(cors.Options{AllowedMethods: []string("GET", "POST", "PUT"})` 

Please test that and write here the results

**Comment by sameersanatkpatro** [comment]
Thanks @kataras for the reply. I have tried this option but I see it still fails.
_"Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3333' is therefore not allowed access. The response had HTTP status code 404."_

**Comment by kataras** [comment]
Yes, after ~4 hours I fixed it, upgrade your iris and the middleware/cors test and tell me the results, ( I tested on dedicated server and it worked)

**Comment by sameersanatkpatro** [comment]
Thanks very much @kataras .It worked.

**Comment by kataras** [comment]
You're welcome, the price is one star to the iris repository, this will help you to be up-to-date for any new changes :)

**Comment by sy264115809** [comment]
I encounter the same question. Here's my code:

```go
app := iris.New()
app.Use(cors.Default())
app.Post("/login", controller.Login) // login

private := app.Party("", middleware.Auth) // add my own auth middleware
resources := private.Party("resources") // create  a party represent a resources endpoint
resources.Get("", controller.List) // list all resource
```

When I send a request from front-end to try to get all resources(`GET /resources`), the Options send by chrome returns that:

> XMLHttpRequest cannot load http://localhost:8898/api/v1/resources. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 404.

I read the source and find out that in https://github.com/kataras/iris/blob/master/http.go#L1205, iris only check the first tree which passes the check of `methodEqual`. Suppose the tree is the `POST tree`,  and the path `/resources` is not added in this tree, so when iris get entry from this tree (https://github.com/kataras/iris/blob/master/http.go#L1162), it CAN NOT get a expected entry, and return `404` in the end of this method.

**Comment by sy264115809** [comment]
BTW, after I removing this line, the problem is resolved: https://github.com/kataras/iris/blob/master/http.go#L1205

**Comment by sy264115809** [comment]
Hi, @kataras 

I encounter the same question mentioned at https://github.com/kataras/iris/issues/486, but I can't comment that issue so I create a new one here. 

Here's my code:

```go
app := iris.New()
app.Use(cors.Default())
app.Post("/login", controller.Login) // login

private := app.Party("", middleware.Auth) // add my own auth middleware
resources := private.Party("resources") // create  a party represent a resources endpoint
resources.Get("", controller.List) // list all resource
```

When I send a request from front-end to try to get all resources(`GET /resources`), the Options send by chrome returns that:

> XMLHttpRequest cannot load http://localhost:8898/api/v1/resources. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 404.

I read the source and find out that in [here](https://github.com/kataras/iris/blob/master/http.go#L1205), iris only check the first tree which passes the check of [`methodEqual`](https://github.com/kataras/iris/blob/master/http.go#L1135). Suppose that the tree is the `POST tree`, iris will not [get a expected entry](https://github.com/kataras/iris/blob/master/http.go#L1162) from this tree since the path `/resources` doesn't be added in this tree, and iris return `404` in the end of this method.

Seems before the request touching the CORS middleware, iris has already rejected it with `404`

After I removing [this line](https://github.com/kataras/iris/blob/master/http.go#L1205), the problem is resolved.
