### ISSUE TITLE
CORS optionPassthrough does not work

### ISSUE THREAD

**Issue by masiqi** [iris-contrib/middleware#15]
I found the code in cors.go changed here
``
pass := c.handlePreflight(ctx) || c.optionPassthrough
if pass {
    ctx.Next()
} else {
    ctx.SetStatusCode(iris.StatusOK)
}
``

if handlePreflight return true it will always exec ctx.Next(),but in fact processing a pre-flight CORS request it should go to ctx.SetStatusCode(iris.StatusOK)

**Comment by kataras** [comment]
Not always, the request method should be "OPTIONS" and `OptionPassthrough` must be true, if it's false it not always exec the ctx.Next(), by-default "OPTIONS" are allowed as routes, but you can disable it via `cMiddleware := cors.New(cors.Options{OptionPassthrough: false }`

**Comment by kataras** [comment]
Not always, the request method should be "OPTIONS" and `OptionPassthrough` must be true, if it's false it not always exec the ctx.Next(), by-default "OPTIONS" are allowed as routes, but you can disable it via `cMiddleware := cors.New(cors.Options{OptionPassthrough: false }` . However I can disable it by-default if that produces unexpected behaviors, I'm waiting for recommendations

**Comment by kataras** [comment]
Not always, the request method should be "OPTIONS" and `OptionPassthrough` must be true, if it's false it not always exec the ctx.Next(), by-default "OPTIONS" are allowed as routes, but you can disable it via `cMiddleware := cors.New(cors.Options{OptionPassthrough: false })` . However I can disable this by-default behavior if that produces unexpected behaviors, I'm waiting for recommendations

**Comment by masiqi** [comment]
I have changed || to && in "c.handlePreflight(ctx) || c.optionPassthrough" ,because handlePreflight always return true i have to set optionPassthrough to false to go to ctx.SetStatusCode(iris.StatusOK),if i don't do that ,it will always go to ctx.Next().

**Comment by kataras** [comment]
Yes, that's should works, I didn't understand what's the problem, if you enable OptionPassthrough it should **always** pass, you enable this option only if you **manually** have registered OPTIONS method for a route handler with `iris.Options("/mypath", myHandler)`

**Comment by kataras** [comment]
Yes, this should be do, if you enable OptionPassthrough it should **always** pass, you enable this option only if you **manually** have registered OPTIONS method for a route handler with `iris.Options("/mypath", myHandler)` , otherwise let it as default to false and it will not pass if handlePreflight return error., I didn't understand where is the problem,
