### ISSUE TITLE
Question: How to manage preflighted CORS

### ISSUE THREAD

**Issue by afboteros** [iris-contrib/middleware#17]
Hi, i'm getting the following error when making a request to Iris with angularjs resource:
```
XMLHttpRequest cannot load http://externalurl.com:3001/action. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.
```

I have CORS configured this way on main.go file:
```
//Cors
iris.Use(cors.New(cors.Options{
	AllowedMethods:     []string{"GET", "POST", "OPTIONS", "HEAD"},
	AllowedOrigins:     []string{"*"},
	AllowedHeaders:     []string{"*"},
	ExposedHeaders:     []string{"*"},
	OptionsPassthrough: true,
	MaxAge:             3600,
}))
```

Any idea what i'm missing here?, thanks for your help.

**Comment by kataras** [comment]
Hello again :)

Can you put the go code snippet for your route and your javascript snippet  in order to be able to debug it? ( aor an example of what you're trying to do in order to test it myself exactly as you are trying to)

Thanks

**Comment by kataras** [comment]
@afboteros I see that you closed the issue, can you write below what was the issue in order other  newcomers developers benefit from your answer?

**Comment by Hany17** [comment]
@afboteros Yes it would be great because we are dealing quite same problem. :)

**Comment by Hany17** [comment]
@kataras  Hello again Kataras. We are facing the same problem. We have main configured like this (anyway I will paste only part that I think is necessary, if you think something is missing just tell me): 
``
// server setup
api := iris.New()
api.Config.DisablePathCorrection = false

c := cors.New(cors.Options{
		AllowedOrigins:   []string{"*"},
		AllowCredentials: true,
		AllowedMethods:   []string{"GET", "POST", "PUT", "DELETE"},
		AllowedHeaders:   []string{"*"},
		Debug:            true,
	})

api.Use(logger.New())
api.Use(c)
api.StaticServe("./uploads", "/bottle/image")

// Routes for cart
cartAPI := api.Party("/cart")
{
	cartAPI.Get("/", cartController.GetOrders)
	cartAPI.Post("/", cartController.Create)
	cartAPI.Put("/:id/:bottleid", cartController.AddOrder)
}
``
And now for example Put method is called like this: 
``
OPTIONS /cart/1/86?count=8 HTTP/1.1
Host: flowdock.eu:8080
Connection: keep-alive
Access-Control-Request-Method: PUT
Origin: https://q2-configurator-1caec.firebaseapp.com
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.89 Safari/537.36
Access-Control-Request-Headers: authorization
Accept: */*
Referer: https://q2-configurator-1caec.firebaseapp.com/configurator/step-three
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: cs-CZ,cs;q=0.8 
``
Btw. in Postman everything works fine but when we call it from the frontend the result is:

``
XMLHttpRequest cannot load https://flowdock.eu:8080/cart/1/86?count=8. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://q2-configurator-1caec.firebaseapp.com' is therefore not allowed access. The response had HTTP status code 404.
`` 
and so on. Thanks for your reply.
