### ISSUE TITLE
OPTIONS 404 on subroute

### ISSUE THREAD

**Issue by mikepc** [iris-contrib/middleware#18]
```
crs := cors.New(cors.Options{
    AllowedOrigins: []string{"*"},
    AllowedMethods: []string{"OPTIONS", "GET", "POST", "PUT", "DELETE"},
    AllowedHeaders: []string{"*"},
})
api := iris.New(c)
api.Use(crs)


tick := api.Party("/om/tickets", authzSupport, loadTicketClient)
{
    tick.Get("/", tickets.OldestUnresponded)
    tick.Get("/:id", authzSupport, loadTicketClient, tickets.GetTicketByID)
    tick.Post("/:id/respond", authzSupport, loadTicketClient, tickets.Respond)

}
```

The OPTIONS call to /:id/respond is 404'ing. I have even tried manually adding a tick.Options() call and iris is still returning a 404 for the options call. 

CORS is operating for the root and detail calls, but not the subroute to details. 

Any help is appreciated.

**Comment by kataras** [comment]
Can you try again with these cors' options and write down the results?
```go
crs := cors.New(cors.Options{
    AllowedOrigins: []string{"*"},
    AllowedMethods: []string{"OPTIONS", "GET", "POST", "PUT", "DELETE"},
    AllowedHeaders: []string{"*"},
   OptionsPassthrough: true,
})

```

**Comment by mikepc** [comment]
No dice, OPTIONS  still 404's

**Comment by mikepc** [comment]
Ok temporarily I have put a Get route. GET is registering properly with CORS, but the POST (and I suspect but haven't tested PUT) doesn't properly register with CORS

**Comment by kataras** [comment]
I don't know what you mean about cors, you maybe mean pure OPTIONS but cors is not pure OPTIONS, anyway I just tested it and it seems to work, I didn't understand your issue but lets wait for someone to make a PR and fix your issue then...

**Comment by macnibblet** [comment]
It's strange because I'm having a similar problem with my setup, tho even with a get for me it does not work.

**Comment by macnibblet** [comment]
Even with OptionsPassthrough enabled and a `.OPTIONS` handler with a panic call I keep geting 405 Method not allowed as if the route does not even exist ? 

P.S. I don't want to have `OptionsPassthrough` enabled

**Comment by kataras** [comment]
Make a PR if you find something strange, this is the community repository, I can't do all alone for a long time more, you have to help to fix your issues..

**Comment by kataras** [comment]
I fixed for my cases, I do not have any issues, maybe the last pr to cors(maden by community member) breaks it, you are free to go and fix it again, make your tests, find what is suits to you, push the pr and I will accept it

**Comment by kataras** [comment]
@macnibblet  @mikepc I have no issues in my tests but I'll try to find what's going on and fix it, meanwhile you're free to make a PR, do not forget, this is repository was created mostly for the community members, it's time to get involved too, thank you!

**Comment by kataras** [comment]
@macnibblet  @mikepc I have no issues in my tests but I'll try to find what's going on and fix it, meanwhile you're free to make a PR, do not forget, this repository was created mostly for the community , it's time to get involved too, thank you!

**Comment by macnibblet** [comment]
@kataras I'm looking for the issue, so far I have tracked it down to `http.go`

**Comment by kataras** [comment]
I have already tried all possible solutions but all of them had side-effects for other routes, for example if we register `OPTIONS` routes if cors is enabled ( we can find it by interface check) then we will have error if more than one route passed as options (GET, POST..=> OPTIONS), so this is not a solution and not good software design, all changes should happen to the middleware itself, do not touch the common core library, try other solutions via middleware or plugin

**Comment by macnibblet** [comment]
@kataras Swapping the collection statements so you have get first and post second works for some strange reason ?

**Comment by macnibblet** [comment]
```go

	// Collection
	app.Get("/users", handlers.getAll)
	app.Post("/users", handlers.create)

	// Resource
	app.Get("/users/:user_id", context.Auth.AssertSameUser, handlers.getById)
	app.Delete("/users/:user_id", context.Auth.AssertAdmin, handlers.remove)

	app.Post("/rpc/user.available", handlers.available)
```

This works, so something is obviously wrong in the path matching ?

**Comment by kataras** [comment]
This is why on my tests all works but yours not... always put GET first, on all languages and frameworks, it founds faster the GET (because it checked first) 

Did you find the solution which will not have side-affects on the `http.go`, because I can't.

**Comment by kataras** [comment]
Make whatever you think right and give me the result here, I can't work with that right now I'm building something more important these days

**Comment by macnibblet** [comment]
Another weird case is when you only have post methods on a specific path CORS does not work on that either...

```go
	app.Get("/authenticate", methodNotAllowedHandler)
	app.Post("/authenticate", authHandlers.user)
	app.Post("/authenticate-application", authHandlers.proxy)
```

This is a kinda ugly solution to get CORS working :/ And I'm not experienced enough to go into the http.go code and mess with the path matching. I'm guessing what we could do is if you register a route with a GET handler we inject a 405 handler prior to adding the new handler and if someone tries to add a get handler after we could throw a panic saying that the get method must be defined first because of performance reasons? 

But silently failing like it's currently doing is not really an acceptable solution ?

**Comment by kataras** [comment]
Look, I will think to inject cors inside the core library in order to have direct access of the cors'options, because right now it hasn't. Please wait some days because this is not my priority

**Comment by kataras** [comment]
Temporary, just put `.Get` first and you should be fine

**Comment by macnibblet** [comment]
Cheers

**Comment by mikepc** [comment]
I appreciate it, man.

For what it's worth it's working fine with the bogus GET route so I don't
care, I don't need a fix asap.

**Comment by murum** [comment]
I'm pretty new to GO, but I feel it pretty strange that it only works for the first kind of Request Method you specify in the routes file. 

See this example:

When this code is active in my routes does only the `auth/login` OPTIONS request returns a 200 and the `auth/user` OPTIONS request returns a 404.
```
// SpecifyRoutes is where we declare the routes at this point
func SpecifyRoutes(apiv1 *iris.Framework) {
	apiv1.Post("/auth/login", Controllers.LoginHandler)
	apiv1.Get("/auth/user", Controllers.GetHandler)
}
```

When I change it to the code below then the `auth/login` OPTIONS request is returned with a 404 and I guess that the `auth/user` OPTIONS request returns a 200.
```
// SpecifyRoutes is where we declare the routes at this point
func SpecifyRoutes(apiv1 *iris.Framework) {
	apiv1.Get("/auth/user", Controllers.GetHandler)
	apiv1.Post("/auth/login", Controllers.LoginHandler)
}
```

Any ideas what's wrong?

**Comment by kataras** [comment]
I'm working on a small surprise for iris core right now, when I find some time I'll take look on this,  meanwhile any PR is welcomed, this is a community repository

**Comment by kataras** [comment]
Update to the new simple, cors middleware with `go get -u github.com/iris-contrib/middleware/cors` and you should be fine :)

**Comment by gtaozheng** [comment]
Try adding:
`app.Options("/api/{any:path}", func(ctx iris.Context) {})`

**Comment by 52fhy** [comment]
``` go
app.Options("/api/{any:path}", func(ctx iris.Context) {
    c.Header("Access-Control-Allow-Origin", c.GetHeader("Origin"))
    c.Header("Access-Control-Allow-Credentials", "true")
    c.Header("Access-Control-Allow-Headers", "X-Requested-With,Content-Type,X-CSRF-Token")
    c.Header("Access-Control-Expose-Headers", "Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers")
    c.Header("Access-Control-Allow-Methods", "GET,PUT,POST,DELETE,OPTIONS")
})
```
