### ISSUE TITLE
i18n: consider using go-i18n

### ISSUE THREAD

**Issue by dalu** [iris-contrib/middleware#2]
https://github.com/nicksnyder/go-i18n

Consider using the above as that package also supports proper plural for each language.
Imho it's the best package currently available for i18n.

Simple translation is good but when you need something like
0 users
1 user
2 users
instead of doing checks in the template why not just let the tool do it that is designed to do it?

The workflow is also straightforward with its command line utility.

**Comment by kataras** [comment]
Yes, I will refactor the i18n as I am writing on the TODOS on kataras/iris repo, thanks you, help me if you can I am doing all alone so far!

**Comment by dalu** [comment]
Is there some kind of init function?
In order for this to work all translation files need to be loaded into memory once.
Can the ```go func New(c Config) iris.HandlerFunc``` be used for this, it should, right?
It's only called once per middleware.
Just want to make sure.

**Comment by dalu** [comment]
https://github.com/dalu/i18n

**Comment by kataras** [comment]
Yes, if you want to load the files before `iris.Listen` once then you should make it as `Plugin` and use the `iris.Plugins.PreListen(func(ir iris.FrameworkAPI){/* do the job here */})`

**Comment by dalu** [comment]
I deleted my public repository since you've edited and deleted my comments.
You're a fraud that has no respect for other people's work

**Comment by kataras** [comment]
I already said to you, that you are not allowed to advertise your packages here, you can do that in chat in private room with me only. What public repository? you didn't made any pull request as I hoped to do. I 'm respect you, you don't respect me.
