### ISSUE TITLE
Get "OPTIONS 404 Not Found" when set static folder

### ISSUE THREAD

**Issue by yobyzal** [iris-contrib/middleware#20]
I test the example code

```
package main

import "github.com/kataras/iris"
import "github.com/iris-contrib/middleware/cors"

func main() {
	app := iris.New()
	app.Use(cors.Default())
	// app.Static("/static", "./static", 1)

	app.Post("/user/create", func(ctx *iris.Context) {
		ctx.Write("POST CREATE")
	})

	app.Listen(":3333")
}
```

It will pass when I send a post request, but fail if uncomment `app.Static("/static", "./static", 1)`. The OPTIONS request will get the status code of "404 Not Found". And get the same result with `OptionsPassthrough: true`.

**Comment by kataras** [comment]
Update to the new simple, cors middleware with `go get -u github.com/iris-contrib/middleware/cors` and you should be fine :)
