### ISSUE TITLE
CORS and Redirection is not working properly?

### ISSUE THREAD

**Issue by pyrostrex** [iris-contrib/middleware#21]
Hi, I'm not sure if this is a bug or not but I hope you can shed some lights :smile:.

For example, I have a WebAPI server such as `http://localhost:1234/users`. 
I then requested in this case using Vue-Resource to `http://localhost:1234/users`.
Iris then automatically redirects me to `http://localhost:1234/users/`.
It then returns me this error in Chrome's Console

```
XMLHttpRequest cannot load http://localhost:1234/users. Redirect from 'http://localhost:1234/users' to 'http://localhost:1234/users/' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:1234' is therefore not allowed access.
```

Here are my Iris implementation example

```go
package main

import (
	"github.com/iris-contrib/middleware/cors"
	"github.com/kataras/iris"
)

func main() {
	iris.Use(cors.Default())
	usersRoute := iris.Party("/users")
	{
		usersRoute.Get("/", handler)
		usersRoute.Post("/", handler)
		usersRoute.Delete("/:id", handler)
	}
	iris.Listen("localhost:1234")
}

func handler(ctx *iris.Context) {
	ctx.JSON(iris.StatusOK, &iris.Map{"success": true})
}
```

**Comment by kataras** [comment]
That's strange, try to clear your browser's history and try again, if doesn't works again please be patient for the next iris version which will support http/2 and all net/http middleware they will be compatible without any special user code  and you will be able to use any cors middleware you used before iris too

**Comment by pyrostrex** [comment]
Yeap sure, tried clearing my browser but still happening. Will wait for the
next iris. Meanwhile I will just directly request `localhost:1234/users/`

**Comment by kataras** [comment]
Update `go get github.com/iris-contrib/middleware/cors` and you should be fine, please verify that the issue is solved :)

**Comment by kataras** [comment]
Update with `go get -u github.com/iris-contrib/middleware/cors` and you should be fine, please verify that the issue is solved :)
