### ISSUE TITLE
CORS Issue on PreFlight Request

### ISSUE THREAD

**Issue by melihmucuk** [iris-contrib/middleware#34]
AllowedMethods don't work.

Error message from React: 

> Failed to load http://localhost:5000/api/v1/auth/login: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.

```
app := iris.New()
app.WrapRouter(cors.WrapNext(cors.Options{
     AllowedOrigins: []string{"*"},
     AllowedMethods: []string{"GET", "POST", "PUT", "PATCH", "DELETE"},
}))
```

**Comment by udtrokia** [comment]
same problem, try koa instead with no errs

**Comment by kataras** [comment]
You have to register your handlers with those methods as well, use `app.Any` instead of `app.Get or app.Post` for example. Router is a different compoment, it's not linked with the cors middleware directly.

**Comment by saeidakbari** [comment]
Hi @kataras @melihmucuk 
It's don't need to register a handler with all methods
just try to implement original CORS library with WrapRouter and it's work perfectly fine
like this:
```
app := iris2.New()

	// Add CORS to application
	app.WrapRouter(cors.New(cors.Options{
		AllowedOrigins:   []string{"*"},
		AllowedHeaders:   []string{"*"},
		AllowCredentials: true,
	}).ServeHTTP)
```

**Comment by kataras** [comment]
@melihmucuk  See https://github.com/kataras/iris/pull/909 for details, @ZaniaDeveloper pushed a solution for that.
