### ISSUE TITLE
jwt post

### ISSUE THREAD

**Issue by CuteLilTwo** [iris-contrib/middleware#45]
Thank you for checking out this issue!Merry Christmas Eve!Hope you have more harvest in the New Year!
And then there's my issue.
I find the jwt demo on this program,`token := ctx.Values().Get("jwt").(*jwt.Token)`,it use the get reqeust.When I use the post request,I put the token into the Header,and get the Header :`token := c.Ctx.Header("Authorization")`,yes I got the token,but how to change the type to the *jwt.Token and to decrypt the token?

**Comment by kataras** [comment]
Hi, sorry for the delay, if you still don't know the answer:

No, you don't understand the `ctx.Values().Get` is to return the token from the middleware/previous handler it has nothing to do with a `Get` request,  the `ctx.Values().Set` sets a value to the request Context temp storage and so on, please read the [kataras/iris/_examples/routing#middleware](https://github.com/kataras/iris/tree/master/_examples/routing#middleware), you will see an example of this right below.
