### ISSUE TITLE
Not resolved jwtHandler.Serve

### ISSUE THREAD

**Issue by Mahdihp** [iris-contrib/middleware#49]
Not resolved jwtHandler.Serve when use Jwt Middelware:
`app := iris.New()
jwtHandler := jwtmiddleware.New(jwtmiddleware.Config{
		ValidationKeyGetter: func(token *jwt.Token) (interface{}, error) {
			return []byte("My Secret"), nil
		},
		SigningMethod: jwt.SigningMethodHS256,
	})
app.Use(jwtHandler.Serve)`

**Comment by kataras** [comment]
Duplicate of: https://github.com/kataras/iris/issues/1269
