### ISSUE TITLE
I can't access my IRIS API from localhost

### ISSUE THREAD

**Issue by EwanValentine** [iris-contrib/middleware#5]
I have the following code... 

```
iris.Use(cors.New(cors.Options{
	AllowedOrigins: []string{"*"},
	AllowedMethods: []string{
		"GET", "OPTIONS", "POST",
		"PATCH", "PUT", "DELETE",
	},
}))
```

However I get a CORS error in my js console? 

```
create:1 Fetch API cannot load http://releases.bandzest.dev/api/v1/releases. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
``` 

However I can access the API from postman, strange.

**Comment by kataras** [comment]
Use `iris.Any` and tell me if that works for you, thanks for your comment !

**Comment by EwanValentine** [comment]
I still can't get this working unfortunately. Where do I use `iris.Any`? Instead of my `iris.Get`? I tried that but got... 

```
Error: Router: Middleware were already registered for the path: '/api/v1/irs' !
```

**Comment by EwanValentine** [comment]
Thanks, got it working!

**Comment by markthethomas** [comment]
@kataras I'm running into this too; is there another way to handle this without using `.Any`? Really don't want to use poor design like that :)

**Comment by kataras** [comment]
@markthethomas Normally, the `OPTIONS` should be valid method if you use the CORS Middleware, https://github.com/kataras/iris/blob/master/http.go#L1508, that doesn't works for you? did you register the middleware after the routes ?

**Comment by intoxicated** [comment]
@kataras it seems like `iris.Get` added options but what about other method like `Put` and `Post`? I just tested on v4.1.1 and it didn't work

**Comment by kataras** [comment]
You have to register each one of the methods with the handler ` iris.Put("/mypath", myHandler);iris.Post("/mypath", myHandler)` if you want to **enable all methods** just write: `iris.Any("/mypath", myHandler)`

**Comment by kataras** [comment]
You have to register each one of the methods with the handler `iris.Options("/mypath", myHandler); iris.Put("/mypath", myHandler);iris.Post("/mypath", myHandler)` if you want to **enable all methods** just write: `iris.Any("/mypath", myHandler)`

**Comment by kataras** [comment]
You have to register each one of the methods with the handler `iris.Options("/mypath", myHandler); iris.Put("/mypath", myHandler);iris.Post("/mypath", myHandler)` if you want to **enable all methods** just write: `iris.Any("/mypath", myHandler)`  . You're responsible and controlling what user is allowed to see on each of the http methods

**Comment by intoxicated** [comment]
@kataras Yep, of course I registered each one of methods with handler in order to make it work. It worked with `iris.Post("/path", handler);` `iris.Options("/path", handler)` on v3, but like you mentioned, I removed options if `Post` or `Put` adds options automatically. Yet it doesn't seem to work out well on v4

**Comment by intoxicated** [comment]
oh wait.. so you mean, unlike `Get`, `Post` or `Put` or any other methods are required to use `Options`???

**Comment by EwanValentine** [comment]
I'm still having big problems with this. I can't seem to just do `api.Post("/myhandler", myHandler)`, it just returns a 404

**Comment by kataras** [comment]
@EwanValentine Try `api.Post("/myhandler", myHandler)` and `api.Options("/myhandler", myHandler)`

**Comment by EwanValentine** [comment]
Unfortunately I'm getting the same result, 404 when hitting the POST route 🤔

**Comment by EwanValentine** [comment]
No, wait! I've sorted it, a combination of that and another bug being bubbled up causing it to 404 in my code. Thanks for your help!!

**Comment by mikepc** [comment]
Some more details on "another bug" would be helpful, I am running into this now as well.

GET for CORS is working fine, but the OPTIONS call to a Post is 404'ing.

I will not wrap the action in Any(), that's just horrible.

**Comment by kataras** [comment]
I don't know what you mean about cors, you maybe mean pure OPTIONS but cors is not pure OPTIONS, anyway I just tested it and it seems to work, I didn't understand your issue but lets wait for someone to make a PR and fix your issue then...
