### ISSUE TITLE
Can't use CORS middleware for iris

### ISSUE THREAD

**Issue by manongguard** [iris-contrib/middleware#54]
i got this as an error when using the example

`cannot use crs (type "github.com/kataras/iris/v12/context".Handler) as type "github.com/kataras/iris/context".Handler in argument to app.APIBuilder.Get`

**Comment by manongguard** [comment]
in order for me to use the middleware i need to use
`github.com/kataras/iris/v12` instead of `github.com/kataras/iris` is this intentional?

**Comment by Birjemin** [comment]
yes, you should do that

**Comment by Dexus** [comment]
hi @kataras 

cors is broken... with v12 i don't get any response on my api...

**Comment by kataras** [comment]
Yes, @manongguard, x/y and x/y/$version are different packages according to [Golang](https://golang.org).  Iris web framework contains extensive [documentation](https://docs.iris-go.com) and [examples](https://github.com/iris-contrib/examples), they all use the new import path.
