### ISSUE TITLE
Can't use csrf and secure middleware

### ISSUE THREAD

**Issue by shshpp** [iris-contrib/middleware#61]
# github.com/iris-contrib/middleware/secure

..\..\..\..\pkg\mod\github.com\iris-contrib\middleware\secure@v0.0.0-20191219204441-78279b78a367\secure.go:94:3: cannot use defaultBadHostHandler (type func("github.com/kataras/iris/v12/context".Context)) as type "github.com/kataras/iris/v12/context".Handler in field value

..\..\..\..\pkg\mod\github.com\iris-contrib\middleware\secure@v0.0.0-20191219204441-78279b78a367\secure.go:133:20: cannot use ctx (type "github.com/kataras/iris/v12/context".Context) as type *"github.com/kataras/iris/v12/context".Context in argument to s.badHostHandler

# github.com/iris-contrib/middleware/csrf

..\..\..\..\pkg\mod\github.com\iris-contrib\middleware\csrf@v0.0.0-20191219204441-78279b78a367\csrf.go:88:24: cannot use unauthorizedHandler (type func("github.com/kataras/iris/v12/context".Context)) as type "github.com/kataras/iris/v12/context".Handler in assignment

..\..\..\..\pkg\mod\github.com\iris-contrib\middleware\csrf@v0.0.0-20191219204441-78279b78a367\csrf.go:143:11: cannot use cs.Serve (type func("github.com/kataras/iris/v12/context".Context)) as type "github.com/kataras/iris/v12/context".Handler in return argument

..\..\..\..\pkg\mod\github.com\iris-contrib\middleware\csrf@v0.0.0-20191219204441-78279b78a367\csrf.go:167:24: cannot use ctx (type "github.com/kataras/iris/v12/context".Context) as type *"github.com/kataras/iris/v12/context".Context in argument to cs.opts.ErrorHandler

..\..\..\..\pkg\mod\github.com\iris-contrib\middleware\csrf@v0.0.0-20191219204441-78279b78a367\csrf.go:175:24: cannot use ctx (type "github.com/kataras/iris/v12/context".Context) as type *"github.com/kataras/iris/v12/context".Context in argument to cs.opts.ErrorHandler

..\..\..\..\pkg\mod\github.com\iris-contrib\middleware\csrf@v0.0.0-20191219204441-78279b78a367\csrf.go:199:25: cannot use ctx (type "github.com/kataras/iris/v12/context".Context) as type *"github.com/kataras/iris/v12/context".Context in argument to cs.opts.ErrorHandler

..\..\..\..\pkg\mod\github.com\iris-contrib\middleware\csrf@v0.0.0-20191219204441-78279b78a367\csrf.go:205:25: cannot use ctx (type "github.com/kataras/iris/v12/context".Context) as type *"github.com/kataras/iris/v12/context".Context in argument to cs.opts.ErrorHandler

..\..\..\..\pkg\mod\github.com\iris-contrib\middleware\csrf@v0.0.0-20191219204441-78279b78a367\csrf.go:214:24: cannot use ctx (type "github.com/kataras/iris/v12/context".Context) as type *"github.com/kataras/iris/v12/context".Context in argument to cs.opts.ErrorHandler

..\..\..\..\pkg\mod\github.com\iris-contrib\middleware\csrf@v0.0.0-20191219204441-78279b78a367\csrf.go:224:24: cannot use ctx (type "github.com/kataras/iris/v12/context".Context) as type *"github.com/kataras/iris/v12/context".Context in argument to cs.opts.ErrorHandler

**Comment by kataras** [comment]
@shshpp To solve this please follow the steps below:

If you want to grab the latest one to match the current master Iris you have to install it, as you fetch the iris with the `@master` suffix:

```sh
$ go mod init myapp
$ go get github.com/kataras/iris/v12@master
$ go get github.com/iris-contrib/middleware/cors@master
```

**Comment by shshpp** [comment]
> 
> 
> @shshpp To solve this please follow the steps below:
> 
> If you want to grab the latest one to match the current master Iris you have to install it, as you fetch the iris with the `@master` suffix:
> 
> ```shell
> $ go mod init myapp
> $ go get github.com/kataras/iris/v12@master
> $ go get github.com/iris-contrib/middleware/cors@master
> ```

thank you very much
