### ISSUE TITLE
github.com/iris-contrib/middleware/jwt update iris.Context to *context.Context

### ISSUE THREAD

**Issue by schooltech** [iris-contrib/middleware#70]
after I update iris to the latest version, jwt handle code occor an error:

Cannot use 'middleware.JwtHandler().Serve' (type func(ctx iris.Context)) as the type context.Handler

`// Serve the middleware's action
func (m *Middleware) Serve(ctx iris.Context) {
	if err := m.CheckJWT(ctx); err != nil {
		m.Config.ErrorHandler(ctx, err)
		return
	}
	// If everything ok then call next.
	ctx.Next()
}`

param of Server ctx.iris.Context should changed to *context.Context

**Comment by kataras** [comment]
@schooltech `iris. Context` is a type alias for `*context.Context` so this is OK :)
